services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
